services:
  - type: web
    name: civicgovgrisoft
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn civic_project.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: civicgovgrisoft-db
          property: connectionString

databases:
  - name: civicgovgrisoft-db
    databaseName: civicgovgrisoft
    user: civicgovgrisoft

